#!/usr/bin/env node

var path = require('path');
var Happner = require('happner');
var config = {
  name: 'server',
  datalayer: {
    host: '127.0.0.1',
    port: 8080
  },

  modules: {
    'happner-files': {
      path: path.dirname(__dirname)
    }

  },
  components: {
    'happner-files': {
      path: {
        routes: {
          '/': __dirname + path.sep + 'files'
        }
      },
      web: {
        routes: {
          // http://localhost:8080/happner-files/files
          files: 'handler'
        }
      }
    }
  }
};

Happner.create(config)
  .then(function(mesh) {
    // console.log(mesh);
  })
  .catch(function(error) {
    console.error(error.stack);
    process.exit(1);
  });
